# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='StuName',
        ),
        migrations.AddField(
            model_name='question',
            name='StuNum',
            field=models.CharField(default='Your Number', max_length=200),
        ),
    ]
